Description: >
    Project: Udacity Cloud DevOps Nanodegree exercise 
    Author: Udacity team
    This template deploys a sample EC2 instance that you can connect through SSH

Paramters:
    EC2KeyPair:
      Description: The key-pair for the sample instance
      Type: String
      Default: "key-pair-us-west-2"

Resources:
    Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
    SecurityGroups:
        - !Ref InstanceSecurityGroup
    KeyName: !Ref EC2KeyPair
    ImageId: 'ami-068663a3c619dd892' # you may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
    InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
    GroupDescription: Enable SSH access via port 22
    SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
