Description: >
  Project: Udacity Cloud DevOps Nanodegree exercise 
  Author: Udacity team
  This template deploys a sample EC2 instance that you can connect through SSH

Parameters:
  EC2KeyPair:
    Description: The key-pair for the sample instance
    Type: String
    Default: "key-pair-us-west-2"

  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'     

Resources:
  EC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0

  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups: 
        - !Ref EC2SecurityGroup
      KeyName: !Ref EC2KeyPair
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: "sample"

