version: 2.1

commands:
  destroy_environment_on_fail:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name ${STACK_NAME}
          when: on_fail

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Stack
          command: |
            aws cloudformation deploy \
              --template-file sample-stack.yml \
              --stack-name ${STACK_NAME}
      - run: return 1
      - destroy_environment_on_fail

workflows:
  my_workflow:
    jobs:
      - create_infrastructure
