# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1


jobs:
  # create_infrastructure:
  #   docker:
  #   - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run:
  #         name: Deploy CloudFormation Stack
  #         command: |
  #           aws cloudformation deploy --template-file sample-stack.yml \
  #           --stack sample-ec2-stack

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["6d:80:32:80:e0:a9:6a:97:07:b5:1f:35:95:ba:69:4f"] # You can get this ID in the section where you registered the SSH Key
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible # install the dependencies needed for your playbook
      - run:
          name: Configure server
          command: |
            export ANSIBLE_HOST_KEY_CHECKING=False
            export ANSIBLE_SSH_HOST_KEY_CHECKING=False
            ansible-playbook -i inventory.txt playbook-remote-web-server.yml


# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  deploy_infrastructure:
    # Run the welcome/run job in its own container
    jobs:
      # - create_infrastructure
      - configure_infrastructure
